#include "bytecode_map.h"

BEGIN_MAP(3, 20)
    MAP_OP(0, CACHE)
    MAP_OP(52, NOP)
    MAP_OP(75, UNARY_POSITIVE)
    MAP_OP(82, UNARY_NEGATIVE)
    MAP_OP(60, UNARY_NOT)
    MAP_OP(13, RETURN_VALUE) // OK
    MAP_OP(50, UNARY_INVERT)
    MAP_OP(3, BINARY_SUBSCR) // ok
    MAP_OP(46, GET_LEN)      // ok
    MAP_OP(54, MATCH_MAPPING)
    MAP_OP(63, MATCH_SEQUENCE)
    MAP_OP(88, MATCH_KEYS)
    MAP_OP(35, PUSH_EXC_INFO)
    MAP_OP(48, CHECK_EXC_MATCH) // ok
    MAP_OP(30, CHECK_EG_MATCH)  // ok
    MAP_OP(36, WITH_EXCEPT_START)
    MAP_OP(64, GET_AITER)         // ok
    MAP_OP(25, GET_ANEXT)         // ok
    MAP_OP(59, BEFORE_ASYNC_WITH) // ok
    MAP_OP(19, BEFORE_WITH)       // ok
    MAP_OP(26, END_ASYNC_FOR)     // ok
    MAP_OP(41, STORE_SUBSCR)
    MAP_OP(15, DELETE_SUBSCR) // ok
    MAP_OP(12, GET_ITER)      // ok
    MAP_OP(16, GET_YIELD_FROM_ITER)
    MAP_OP(1, PRINT_EXPR)
    MAP_OP(28, LOAD_BUILD_CLASS)
    MAP_OP(73, PUSH_NULL) // ok
    MAP_OP(74, LOAD_ASSERTION_ERROR)
    MAP_OP(42, RETURN_GENERATOR)
    MAP_OP(78, POP_TOP) // OK
    MAP_OP(27, LIST_TO_TUPLE)
    MAP_OP(24, IMPORT_STAR)
    MAP_OP(61, SETUP_ANNOTATIONS)
    MAP_OP(40, YIELD_VALUE)
    MAP_OP(66, ASYNC_GEN_WRAP) // ok
    MAP_OP(9, PREP_RERAISE_STAR)
    MAP_OP(31, POP_EXCEPT)
    MAP_OP(90, STORE_NAME_A)   // ok
    MAP_OP(130, DELETE_NAME_A) // ok
    MAP_OP(233, UNPACK_SEQUENCE_A)
    MAP_OP(110, FOR_ITER_A) // ok
    MAP_OP(174, UNPACK_EX_A)
    MAP_OP(94, LOAD_FAST_A) // OK
    MAP_OP(213, STORE_ATTR_A)
    MAP_OP(131, DELETE_ATTR_A) // ok
    MAP_OP(230, STORE_GLOBAL_A)
    MAP_OP(185, DELETE_GLOBAL_A) // ok
    MAP_OP(193, SWAP_A)
    MAP_OP(100, STORE_FAST_A)
    MAP_OP(122, BUILD_TUPLE_A) // ok
    MAP_OP(205, BUILD_LIST_A)  // ok
    MAP_OP(224, BUILD_SET_A)   // ok
    MAP_OP(204, BUILD_MAP_A)   // ok
    MAP_OP(222, LOAD_ATTR_A)
    MAP_OP(119, COMPARE_OP_A) // ok
    MAP_OP(236, IMPORT_NAME_A)
    MAP_OP(108, LOAD_GLOBAL_A)
    MAP_OP(237, IMPORT_FROM_A)
    MAP_OP(184, JUMP_FORWARD_A)
    MAP_OP(101, JUMP_IF_FALSE_OR_POP_A)
    MAP_OP(109, JUMP_IF_TRUE_OR_POP_A)
    MAP_OP(188, POP_JUMP_FORWARD_IF_FALSE_A)
    MAP_OP(134, POP_JUMP_FORWARD_IF_TRUE_A)
    MAP_OP(144, IS_OP_A)
    MAP_OP(223, CONTAINS_OP_A) // ok
    MAP_OP(173, RERAISE_A)
    MAP_OP(221, COPY_A)      // ok
    MAP_OP(125, BINARY_OP_A) // ok
    MAP_OP(103, SEND_A)
    MAP_OP(133, DELETE_FAST_A) // ok
    MAP_OP(168, POP_JUMP_FORWARD_IF_NOT_NONE_A)
    MAP_OP(116, POP_JUMP_FORWARD_IF_NONE_A)
    MAP_OP(123, RAISE_VARARGS_A)
    MAP_OP(225, GET_AWAITABLE_A) // ok
    MAP_OP(132, MAKE_FUNCTION_A)
    MAP_OP(140, BUILD_SLICE_A) // ok
    MAP_OP(220, JUMP_BACKWARD_NO_INTERRUPT_A)
    MAP_OP(166, MAKE_CELL_A)
    MAP_OP(177, LOAD_CLOSURE_A)
    MAP_OP(118, LOAD_DEREF_A)
    MAP_OP(150, STORE_DEREF_A)
    MAP_OP(120, DELETE_DEREF_A) // ok
    MAP_OP(142, JUMP_BACKWARD_A)
    MAP_OP(143, CALL_FUNCTION_EX_A) // ok
    MAP_OP(240, EXTENDED_ARG_A)     // ok
    MAP_OP(161, LIST_APPEND_A)
    MAP_OP(169, SET_ADD_A)
    MAP_OP(155, MAP_ADD_A)
    MAP_OP(200, LOAD_CLASSDEREF_A)
    MAP_OP(192, COPY_FREE_VARS_A) // ok
    MAP_OP(104, MATCH_CLASS_A)
    MAP_OP(112, FORMAT_VALUE_A)        // ok
    MAP_OP(147, BUILD_CONST_KEY_MAP_A) // ok
    MAP_OP(197, BUILD_STRING_A)        // ok
    MAP_OP(160, LOAD_METHOD_A)
    MAP_OP(228, LIST_EXTEND_A)
    MAP_OP(106, SET_UPDATE_A)
    MAP_OP(153, DICT_MERGE_A)  // ok
    MAP_OP(210, DICT_UPDATE_A) // ok
    MAP_OP(172, PRECALL_A)     // OK
    MAP_OP(211, KW_NAMES_A)
    MAP_OP(165, POP_JUMP_BACKWARD_IF_NOT_NONE_A)
    MAP_OP(121, POP_JUMP_BACKWARD_IF_NONE_A)
    MAP_OP(163, POP_JUMP_BACKWARD_IF_FALSE_A)
    MAP_OP(145, POP_JUMP_BACKWARD_IF_TRUE_A)
    MAP_OP(196, LOAD_NAME_A)     // ok
    MAP_OP(202, LOAD_CONST_A)    // ok
    MAP_OP(206, MAKE_FUNCTION_A) // ok
    MAP_OP(214, RESUME_A)        // ok
    MAP_OP(226, CALL_A)          // OK
END_MAP()
